---
title: "Plotly"
---
## Question:
### Which application generally costs the most energy in a normal household?

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(plotly)
sums <- read.csv("sums.csv")
fig <- plot_ly(sums, x = ~date, y = ~sum,
               color = ~category,
               type='scatter', mode='lines',
               hovertemplate=paste('<b>',sums$category,'</b><br>Date=%{x}<br>Sum=%{y:.2f}')) %>% 
  plotly::layout(xaxis=list(title='Date'),
         yaxis=list(title='Summation'),
         title = 'Total Expenditure of Energy',
         showlegend=FALSE)
fig
```


From the graph above, we can perceive that it is entertainment that generally costs the most energy in a specific household. This fact is
totally reasonable, for currently laptop, cellphone, or TV have already been one of the most significant organs that we cannot lose. Through 
Facebook, Netflix, Tiktok and etc, we gain cheap satisfaction continuously. However, if human beings as a group would like to save energy
to prevent greenhouse gas emission, we should consider to appropriately lower our daily time of entertainment with electronic devices.


In my design, I combined data from all seven application usage and electric expenditure from home 06, get the sum of these usages, and construct
a new dataframe. From this dataframe, I show the summation of electric expenditures everyday by different categories. Then when reaching each line,
you can also notice that I label the exact category, date, and summation at each point, so that you can figure out the exact value at each position.
